name: Cherry Pick to 12.x

on:
  push:
    branches:
      - main

jobs:
  call_reusable_workflow:
    uses: ./.github/workflows/cherry-pick.yml
    with:
      source_branch: 'main'
      target_branch: '12.x'
