name: Cherry Pick to 12.x

on:
  push:
    branches:
      - main

jobs:
  call_reusable_workflow:
    uses: ./.github/templates/cherry-pick.yml
    with:
      commit_from: ${{ github.event.before }}
      commit_to: ${{ github.event.after }}
      target_branch: '12.x'
