name: Release 12.x

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version type'
        required: true
        type: choice
        options:
          - patch
          - minor

jobs:
  create-release:
    uses: ./.github/templates/create-release.yml
    with:
      new_version: ${{ inputs.version }}
      target_branch: '12.x'

  publish-to-npm:
    needs: create-release
    uses: ./.github/templates/publish-to-npm.yml
    with:
      target_branch: '12.x'
